openapi: 3.0.3
info:
  title: Choreo Samples - Reading List - Nodejs REST API
  description: >-
    This is a sample API specification for a simple reading list application with in-memory cache
    written in Nodejs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:8080
tags:
  - name: books
    description: In-memory book list cache API
paths:
  /patientList:
    summary: Testing route1
    get:
      summary: Testing route1
      operationId: patientList
      responses:
        "200":
          description: Successful operation
        "404":
          description: failed operation
  /getRouteTheme:
    summary: Testing route2
    get:
      summary: Testing route2
      operationId: getRouteTheme
      responses:
        "200":
          description: Successful operation
        "404":
          description: failed operation
  /addRouteTheme:
    summary: Testing route3
    post:
      summary: addRouteTheme
      operationId: addRouteTheme
      responses:
        "200":
          description: Successful operation
        "404":
          description: failed operation
components:
  schemas:
    Key:
      type: object
      properties:
        uuid:
          type: string
          example: "my-uuid"
    Status:
      type: object
      properties:
        status:
          type: string
          example: "read"
    KeyValue:
      type: object
      required:
        - title
        - author
        - status
      properties:
        title:
          type: string
          example: "my-title"
        author:
          type: string
          example: "my-author"
        status:
          type: string
          example: "read"
    StringArray:
      type: array
      items:
        type: string
